### PR TITLE
JSS v15 variation for Sitecore 10 containers

### PR DESCRIPTION
**Pull request by vtml**
1. Creates different JSS version variations for Sitecore v10 - ie v14, v15
2. Container tags without JSS version specified is the latest JSS version

This PR addresses the issue https://github.com/Sitecore/docker-images/issues/402

### CODE REVIEW

**Comment by jeanfrancoislarente** [comment]
@bplasmeijer - I've updated w/ Linux images. Built both Linux and Windows (ltsc2019) images. 

Please have a review when you have a chance. Thanks!

**Comment by bplasmeijer** [comment]
WIP

**Review by jeanfrancoislarente — COMMENTED** [review]
Thanks for the QA (and finding an issue) @bplasmeijer !

**Review by bplasmeijer — APPROVED** [review]

**Comment by jeanfrancoislarente** [comment]
Fixes #402

**Pull request merged**
