### PR TITLE
Add missing volume declaration for cd/cm containers

### PR DESCRIPTION
**Pull request by sshushliapin**
For some reason log volumes are not mapped for most of the CM/CD containers (all except commerce). Hope they have not been removed for purpose ;)

This PR restores CM/CD log volumes.

### CODE REVIEW

**Comment by pbering** [comment]
Hi, they have indeed been removed on purpose :)

The test compose files uses the entrypoint scripts that output all the logs to STDOUT so now there is no need to also persist the log files to a volume. You can just use the `docker container logs` to get/follow them if you run the containers in the background.

**Comment by sshushliapin** [comment]
Got it. Anyway, anyone can change it locally at any time ;)

I noticed that xconnect still write logs to files/volumes? Is that smth that might need to be changed to STDOUT as well?

**Comment by pbering** [comment]
Exactly :) ... the xconnect specific entrytpoints already outputs logs to STDOUT so the volume is not needed there either and should be removed from the compose files.

**Comment by sshushliapin** [comment]
Closing this one as not required.

**Pull request closed without merging**
