### PR TITLE
Add ContainerDeployment package version 027

### PR DESCRIPTION
**Pull request by sc-jonasbangchristensen**
This commit adds the initial version (027) of the Container Deployment Support package for Sitecore 10.0.

With this we effectively move the Container Deployment Support package from dev.sitecore.net to GitHub.

### CODE REVIEW

**Comment by jballe** [comment]
Just my five cent for this conversation...

I am all in for using GitHub instead of dev.sitecore.net!! 
It is way easier to use and follow updates, so thank you for that! 💪

I am wondering if this repository is the right place for the Container Deployment Support package, even though it is related Sitecore and docker images it is a different use case, it is not about having/building the images it is about using them and have a starting point for that. I would expect that those two parts will evolve differently with another engagement and release cycles and completely different build pipeline.

From my point of view, I would prefer a dedicated repository for the Container Deployment Support package. 
This would let the contributors of each part/repository focus on the right pieces and enable even more scenarios. I could image that those starting points for Kubernetes could evolve to real helm charts and have build actions/pipelines that create releases so we can consume those as helm repositories. A bit like what is now going on in the [sitecore-helm repository](https://github.com/sitecoreops/sitecore-helm). I know that is not what we have right now but eg. tagging can let us find the current version and still evolve.
I am afraid that if staying together with the docker images the support package will be more like an under prioritized second citizen while it actually provides a lot of value and deserve way more focus than it would have in this repository.

There can of course be other reasons that I am not aware of right now, so I am not saying that it is wrong to have it here, I am just worried.

**Comment by sc-jonasbangchristensen** [comment]
Thanks for your input @jballe. We will put this PR on hold, and reconsider the best approach forward for moving the Container Deployment Support package from dev.sitecore.net to GitHub.

**Comment by jeanfrancoislarente** [comment]
Great feedback @jballe and not unlike what we were toying with internally.

Our initial intent was to try to keep as much of the container-related stuff together in this repo but @sc-jonasbangchristensen  and @dmositecore definitely shared your opinion from the start.

The proposal is to create a new github repo now: `sitecore/container-deployment` which would hold everything relevant to the _deployment_ of Sitecore, rather than the image building.

The structure we're toying with is as follows, and we're hoping to get some feedback before going through all of the steps:

```
k8s/
    sxp/ (tag group)
        10.0/
            ltsc2019/
                xm1/
                xp1/
        10.1/
    sxc/
        10.0/
        10.1/
    sxa/
        10.0/
            ltsc2019/
                xm1/
                xp1/
compose
    sxp/
        10.0/
            1909/
                xm1/
                xp0/
                xp1/
            ltsc2019/
                xm1/
                xp0/
                xp1/
        10.1/
        10.2/
    sxc/
        10.0/
        10.1/
experimental/ (demo, community, unsupported)
    helm/
        sxp/ (tag group)
            10.0/
```

**Comment by bplasmeijer** [comment]
I ask the community for feedback.

**Pull request closed without merging**
