### PR TITLE
Use InstallSourcePath to store converted .scwdp package

### PR DESCRIPTION
**Pull request by sshushliapin**
Addresses #262.

### CODE REVIEW

**Comment by sshushliapin** [comment]
I removed some 9.2 ps images in order to fix builds. It seems they were committed by mistake because there are much more 9.2 ps images needed in order to make it working.

**Comment by sshushliapin** [comment]
JFI, "Works on my CI" ;)

All Sitecore versions starting from 9.0.2 + All windows versions + Experimental packages

image

**Comment by jeanfrancoislarente** [comment]
Which build pipeline are you using? The one in Joost's PR or the one in master? or your own?

**Comment by sshushliapin** [comment]
Master + these my two commits to be able build experimental packages.

**Comment by bplasmeijer** [comment]
---testing---

**Comment by bplasmeijer** [comment]
- please rebase with origin/master
- I will check again after rebase

**Comment by bplasmeijer** [comment]
please check @jeanfrancoislarente , if still valid, otherwise close PR

**Comment by sshushliapin** [comment]
Looks like `master` works fine now so this PR can be closed.

**Pull request closed without merging**
