### PR TITLE
Change validity for generated certificates to be 10 years instead of 1

### PR DESCRIPTION
**Pull request by GurliGebis**
Currently the sitecore-certificates dockerfile generates certificates that is valid for 1 year.

To prevent having to regenerate the images after a year, it would be better to change the validity to be for a longer period of time.

Having it on 10 years, it would be possible to use the same images for the lifetime of a Sitecore release.

### CODE REVIEW

**Comment by pbering** [comment]
Hi there! All of our images should be rebuilt regularly (for example weekly) to get the latest base images with latest Windows Updates, so the certs for 9.2/9.1 will be recreated and renewed. So I don't think this PR is needed...

**Comment by GurliGebis** [comment]
Since it is being used for development in an isolated environment, what reason is there to rebuild them all the time with the latest Windows Updates?

**Comment by pbering** [comment]
for the same reasons as why you are updating your other machines, for security and other improvements :)

**Comment by GurliGebis** [comment]
Seems like we should look into having a pipeline to rebuild the images, so they keep getting updated then.

I'll close the PR, since it does not make sense to have it being longer if the images has to be rebuilt every month anyway.

**Pull request closed without merging**
