### PR TITLE
Feature/sxa+jss

### LINKED ISSUE #125: Add SXA+JSS Containers for XM and XP.

### PR DESCRIPTION
**Pull request by peternazarov**
Resolves #125

### CODE REVIEW

**Comment by bplasmeijer** [comment]
please update docs ; Update-Documentation.ps1

**Comment by gbxe** [comment]
Hi @bplasmeijer 

I have updated the documentation as suggested. Please Review.

**Comment by gbxe** [comment]
Note: https://github.com/Sitecore/docker-images/pull/131 modifies the original Drokcer files that have been duplicated with this PR. I copies fo the JSS Docker files. However, there were no changes needed to made to them.

Can somebody please advise whether we shall be reusing Docker files in this case instead of copying them and if so how to implement the Docker file reuse? It would be good to align on the approach.

- `windows/9.2.x/sitecore-xm-sxa-jss/Dockerfile` should  be the same as `windows/9.2.x/sitecore-xm-jss/Dockerfile`
- `windows/9.2.x/sitecore-xp-sxa-jss/Dockerfile` should  be the same as `windows/9.2.x/sitecore-xp-jss/Dockerfile`

**Comment by jeanfrancoislarente** [comment]
Hey @gbxe 

As discussed on #docker in Slack (adding here for completeness). You can likely accomplish this by modifying `build.json` of `sitecore-xp-jss` and `sitecore-xm-jss` to include two new tag objects.

You would then change the "tag" to include `sxa` (ie: `sitecore-xp-sxa-jss-standalone`) and the BASE image would change to the relevant SXA image (ie: `sitecore-xp-sxa-standalone:`)
Example new tag (unverified):

```json
 {
      "tag": "sitecore-xp-sxa-jss-standalone:9.2.0-windowsservercore-${windowsservercore_version}",
      "build-options": [
        "--build-arg BASE_IMAGE=sitecore-xp-sxa-standalone:9.2.0-windowsservercore-${windowsservercore_version}",
        "--build-arg ASSETS_IMAGE=sitecore-assets:9.2.0-nanoserver-${nanoserver_version}",
        "--build-arg ASSETS_USE_WDP='C:\\packages\\Sitecore JavaScript Services Server for Sitecore 9.2 XP 12.0.0 rev. 190522.scwdp.zip'",
        "--build-arg SC_ROLE_CONFIG_DIRECTORY=\\config\\cm",
        "--build-arg SC_ROLE_DEFINE='Standalone'"
      ]
    }
```


(thanks @pbering )

**Comment by gbxe** [comment]
> Note: #131 modifies the original Drokcer files that have been duplicated with this PR. I copies fo the JSS Docker files. However, there were no changes needed to made to them.
> 
> Can somebody please advise whether we shall be reusing Docker files in this case instead of copying them and if so how to implement the Docker file reuse? It would be good to align on the approach.
> 
> * `windows/9.2.x/sitecore-xm-sxa-jss/Dockerfile` should  be the same as `windows/9.2.x/sitecore-xm-jss/Dockerfile`
> * `windows/9.2.x/sitecore-xp-sxa-jss/Dockerfile` should  be the same as `windows/9.2.x/sitecore-xp-jss/Dockerfile`

Fixed:
 - Allowed to specify `Docker` file relative path in `build.json`.
 - Updated `build.json` for `jss+sxa` XM & XP images so that they use the corresponding `Docker` files from `jss` XM and XP images.

**Comment by pbering** [comment]
Can you help me understand the changes with "dockerFileRelativePath", I don't yet understand why that are needed? You have both xm-jss and xm-sxa-jss in windows/9.2.x/sitecore-xm-jss/build.json.

**Comment by gbxe** [comment]
Hi @pberibg

The reason why "dockerFileRelativePath" changes are needed is explained in my previous comments. They address the challenges related to PR #131.

I am not sure why do you mention `windows/9.2.x/sitecore-xm-jss/build.json` file in the context of `xm-sxa-jss`. This file is not modified by this PR and it does not have any reference to SXA. 

This PR aims to introduce the Docker images for XM and XP that have SXA and JSS modules installed.

**Comment by pbering** [comment]
Ok thanks, I get it now, it's related to the installation of node.js in #131. 

I think that it would be better to make a copy the "xm-sxa" folder into "xm-sxa-jss" and then install node and jss so we can avoid the "dockerFileRelativePath" changes, so each folder can be build in isolation. Right now there are only one build-args for specifiying which WDP to install `ASSETS_USE_WDP`, that will need to be changed into two different, for example `ASSETS_USE_WDP_1` and `ASSETS_USE_WDP_2`.

For the "xm-sxa-jss-dev" you can reuse the existing "xm-jss-sqldev" folder and add a new tag like: https://github.com/ValtechDK/sitecore-docker-images/blob/sxajsstest/windows/9.2.x/sitecore-xm-jss-sqldev/build.json#L13

**Comment by bplasmeijer** [comment]
@peter-nazarov-namics-com  can you rebase with master

**Comment by bplasmeijer** [comment]
please rebase with master

**Comment by peternazarov** [comment]
@bplasmeijer, Rebased and removed a legacy build order changes commit...

**Comment by peternazarov** [comment]
Now includes the changes from https://github.com/Sitecore/docker-images/pull/131

**Comment by bplasmeijer** [comment]
please rebase master

**Comment by peternazarov** [comment]
Rebased on 'master.

**Comment by bplasmeijer** [comment]
merged with #232

**Pull request closed without merging**
