### PR TITLE
Update to support 2009

### PR DESCRIPTION
**Pull request by chowson**
# Pull Request Checklist

## Image Details

- [ Y ] I have added NEW image tags
- [ N ] I have made significant changes to existing images

## Pull Request Details

**What this PR does / why we need it**:
20H2 support to allow running in process isolation.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

## Pre-submit Checklist

- [ Y ] I have read and am familiar with the contents of [CONTRIBUTING.md](https://github.com/Sitecore/docker-images/blob/master/CONTRIBUTING.md)
- [ Y ] I have built the images locally (all relevant OS versions, including Linux if applicable)

  - Include the `.\build.ps1` command used (don't forget to exclude your credentials!)

.\Build.ps1 -InstallSourcePath C:\temp -SitecoreUsername XXX -SitecorePassword XXX -SitecoreVersion 9.2.0 -OSVersion 20H2 -Topology xm

  - Ensure the build was done on a clean system (`docker system prune -af`)

- [ N/A ] I have added or updated the necessary docker-compose file(s) in the `build/windows/tests` folder
- [ Y ] I have updated the documentation using `build\update-documentation.ps1`
- [ Y ] I have updated the `build\CHANGELOG.md` with details about the change(s) included

### CODE REVIEW

**Comment by jeanfrancoislarente** [comment]
Hey @chowson,

Please remove any changed files from /tags (ie: sitecore-tags.md). This folder is modified only by Sitecore internal build process.

There is a known issue with line endings which is causing the file to appear as being changed on checkout/clone. To reset the file's state (assuming you have no other pending changes open at the time) you can execute the following lines:

```
git rm .gitattributes
git add -A
git reset --hard
```

**Comment by chowson** [comment]
I think that must have happened during running `.\build\Update-Documentation.ps1`. I've reverted that file and updated the commit.

**Comment by chowson** [comment]
@jeanfrancoislarente - Do you have any estimate on when this will get reviewed/merged?

**Comment by jeanfrancoislarente** [comment]
> @jeanfrancoislarente - Do you have any estimate on when this will get reviewed/merged?

Hey @chowson, just ran this against v10 and it failed due to the fact that Sitecore tags are still 2009, rather than 20H2. I've brought this up internally and they're still working on the process.

**Comment by jeanfrancoislarente** [comment]
@chowson - please temporarily update tags to 2009 from 20H2. Sitecore is working on getting the 20H2 tags released but we could move forward w/ 2009 for now.

**Review by jeanfrancoislarente — APPROVED** [review]
Tested w/ 10.0 and built succesfully.

**Pull request merged**
