### PR TITLE
Fixes v10 JSS and SXA CD web.config transforms, installs NodeJS into JSS containers

### PR DESCRIPTION
**Pull request by vtml**
# Pull Request Checklist

## Image Details

- [ ] I have added NEW image tags
- [ ] I have made significant changes to existing images

## Pull Request Details

**What this PR does / why we need it**:
NodeJS is not installed to the JSS CM / CD Docker containers, which causes integrated mode to fail.
Web.config transform was not run for JSS containers, and SXA CD containers

**Which issue(s) this PR fixes**:
Fixes https://github.com/Sitecore/docker-images/issues/386
Fixes https://github.com/Sitecore/docker-images/issues/387

**Special notes for your reviewer**:
I am taking inspiration from the 9.3 setup.
https://github.com/Sitecore/docker-images/blob/4e76e6f2317d2d70975b25814a6350e30968f273/build/windows/9.x.x/sitecore-jss/Dockerfile#L34
https://github.com/Sitecore/docker-images/blob/4e76e6f2317d2d70975b25814a6350e30968f273/build/windows/9.3.0/sitecore-assets/Dockerfile#L10

I have successfully imported the Sitecore JSS React Sample application into the CM SXA+JSS container. Experience Editor is also functioning as it should.

## Pre-submit Checklist

- [x] I have read and am familiar with the contents of [CONTRIBUTING.md](https://github.com/Sitecore/docker-images/blob/master/CONTRIBUTING.md)
- [x] I have built the images locally (all relevant OS versions, including Linux if applicable)

  - Include the `.\build.ps1` command used (don't forget to exclude your credentials!)

```powershell
.\Build.ps1 -InstallSourcePath -SitecoreUsername "fdsa" -SitecorePassword "fdsa" -OSVersion @("2004", "1909", "ltsc2019") -IncludeSpe -IncludeSxa -IncludeJss -SkipExistingImage
```
  - Ensure the build was done on a clean system (`docker system prune -af`)

- [ ] I have added or updated the necessary docker-compose file(s) in the `build/windows/tests` folder
- [ ] I have updated the documentation using `build\update-documentation.ps1`
- [x] I have updated the `build\CHANGELOG.md` with details about the change(s) included

### CODE REVIEW

**Comment by KKings** [comment]
@vtml - The only thing I can see as a potential issue is not setting the PATH to the node.js installation as was done in previous versions - Experience Editor had some issues with finding the path correctly. Something like below worked in my images:

`RUN $env:PATH = 'C:\nodejs;{0}' -f $env:PATH ; `
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)
RUN npm config set registry https://registry.npmjs.org/
`

**Comment by vtml** [comment]
Just received some feedback from @jflheureux on Slack. I will remove the NodeJS installation from the container, and instead providing example docker-compose files / dockerfile layer to install the appropriate version of NodeJS, if/when required.

**Comment by jeanfrancoislarente** [comment]
Thanks @vtml   I just happened to ping @bplasmeijer to take a look at this one tomorrow. @jflheureux  feedback makes sense and sorry nobody looked at it before today!

**Comment by vtml** [comment]
@bplasmeijer / @jflheureux / @jeanfrancoislarente this is now done.

**Comment by jeanfrancoislarente** [comment]
Please rebase and squash against master @vtml see [Contributing.md](https://github.com/Sitecore/docker-images/blob/master/CONTRIBUTING.md#submitting-pull-requests)

**Comment by vtml** [comment]
I hate squashing commits 😡 
Replaced by PR https://github.com/Sitecore/docker-images/pull/469

**Pull request closed without merging**
