### PR TITLE
Aligned `/tools/` directory contained scripts implementation with Sit…

### LINKED ISSUE #425: `/tools/` directory contained scripts implementation are not aligned with new Sitecore Official Version 10.0.0 implementation
`/tools/` directory contained scripts implementation are not aligned with new Sitecore Official Version 10.0.0 implementation (source Docker image: scr.sitecore.com/tools/sitecore-docker-tools-assets:10.0.0-1809) so that the implementation mismatches.

### PR DESCRIPTION
**Pull request by peter-nazarov-namics-com**
Fix #425 

Aligned `/tools/` directory contained scripts implementation with Sitecore Official Version 10.0.0 implementation (source Docker image: scr.sitecore.com/tools/sitecore-docker-tools-assets:10.0.0-1809) so that the implementation matches, as much as it makes sense (as previously discussed with @pbering).

### CODE REVIEW

**Comment by peter-nazarov-namics-com** [comment]
Hi @jeanfrancoislarente 

Regarding file system deletion event handling. I preserved the deletion attempts wait timings as we had them before in community version. I discussed and aligned those timing values with @pbering previously before @pbering  merged them in as part of my original PR some time ago.

**Comment by jeanfrancoislarente** [comment]
Hey @peter-nazarov-namics-com - the contents of the sitecore-docker-tools-assets will soon be available in a separate repo. I think it might make sense to abandon this PR?

**Comment by peter-nazarov-namics-com** [comment]
Hey @jeanfrancoislarente 

It would make sense, indeed. However, I would say as soon as they will...

Though, it is totally up to you. I would not mind if you decide to close it.

**Comment by jeanfrancoislarente** [comment]
@peter-nazarov-namics-com - I created a new PR !545 to remove the tools from the asset image in 10+

**Pull request closed without merging**
