### PR TITLE
Fixed issue where too many images are included.

### PR DESCRIPTION
**Pull request by michaellwest**
Changes included the build.ps1

* `IncludeJss` is requried for any Jss image to be built, especially those bundled with Sxa
* You can now use `OnlyList` to see what will be built.

### CODE REVIEW

**Comment by michaellwest** [comment]
That's expected. The `sitecore-assets` image was never changed to separate by topology.

**Comment by bplasmeijer** [comment]
can you rebase @michaellwest

**Comment by michaellwest** [comment]
@bplasmeijer Done.

**Comment by coreyasmith** [comment]
Would it make sense to drop the `OnlyList` switch in favor of using `WhatIf`?

**Review by jeanfrancoislarente — CHANGES_REQUESTED** [review]
Hey @michaellwest  - can you rebase and update the PR - I'll merge this one in.

**Comment by bplasmeijer** [comment]
I think we close this PR @michaellwest 

cc: @jeanfrancoislarente

**Pull request closed without merging**
