### PR TITLE
Fix Azure Devops pipeline build

### PR DESCRIPTION
**Pull request by joostmeijles**

### CODE REVIEW

**Comment by bplasmeijer** [comment]
@jeanfrancoislarente can you sync with @joostmeijles

**Comment by joostmeijles** [comment]
@jeanfrancoislarente please review. Merge conflicts are fixed, and changes are now mostly about more consistent naming and an overview of what variables to set.

**Comment by joostmeijles** [comment]
@jeanfrancoislarente I do no longer plan to use the Azure Devops build. Will rely on a local build for 9.3 and on the official Sitecore registry for newer versions instead.

From my pov this PR may be closed.

**Comment by jeanfrancoislarente** [comment]
Thanks @joostmeijles - still good improvements to be included. Just hasn't been a priority due to the fact that right now it works correctly as-is. I will get to this at some point

**Comment by jeanfrancoislarente** [comment]
Closing - replaced by a rebased #273 . Thanks @joostmeijles !!

**Pull request closed without merging**
