### PR TITLE
COPY instead of ADD + Environment variable SITEPATH

### PR DESCRIPTION
**Pull request by Ben-m-s**
Changes done to Dockerfiles for SC 9.0.1 rev. 171219
- Create SITEPATH variable to centralize definition of Website folder
- Replace ADD with COPY to follow best practices: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

### CODE REVIEW

**Comment by Ben-m-s** [comment]
Requested changes have been done. Any reason why this shouldn't be applied also to versions 8.2?

**Comment by pbering** [comment]
No reason, as I wrote it should be "at least the major versions" so I would be even nicer if it was for everything :) ... interested in doing it? Else I will approve this pull request as is.

**Comment by Ben-m-s** [comment]
The change shouldn't take long and it would be nice to have. I will do it today.

**Comment by Ben-m-s** [comment]
Done!

**Comment by pbering** [comment]
@jeanfrancoislarente please merge this when you have time

**Comment by jeanfrancoislarente** [comment]
Awesome thanks!!

**Pull request merged**
