### PR TITLE
First iteration of publishing service image (v4.1)

### PR DESCRIPTION
**Pull request by mjftechnology**
Initial version of Publishing Service images.

Connection strings configurable in env file allowing one image to serve multiple Sitecore databases without rebuilding.

Jean Francois asked me to raise this PR a while back, please let me know any comments, suggestions or improvements you have

### CODE REVIEW

**Comment by bplasmeijer** [comment]
I am processing 4.2 release at the moment; let me compare with yours today.

**Comment by bplasmeijer** [comment]
Hi Matt, Let see if I can merge next to the 4.2 release

**Comment by bplasmeijer** [comment]
please rebase master

**Comment by pbering** [comment]
I will close this PR as we have it now.

**Pull request closed without merging**
