### PR TITLE
Updating builds that leverage SPE 6.0 to use 6.1.1

### PR DESCRIPTION
**Pull request by bic742**

### CODE REVIEW

**Comment by bplasmeijer** [comment]
@michaellwest any risk on 9.3 SXA?

**Comment by michaellwest** [comment]
This should work fine. I've been testing with 9.3 for a while now. Thanks for checking.

**Comment by bplasmeijer** [comment]
We cannot merge now because we do not include module specified tagging on the images.
The topic is on our agenda.

**Comment by michaellwest** [comment]
Sounds like a good opportunity for labels.

**Comment by michaellwest** [comment]
Why is it flagged as a breaking change?

**Comment by pbering** [comment]
@michaellwest with our current tagging convention for variant images _without_ the version number of the different modules, we will break current Sitecore databases that is persisted on peoples machines or in Swarm/Kubernetes.

Example: 

1. `docker image pull sitecore-xm-spe-sqldev:9.3.0-windowsservercore-ltsc2019`
1. run it and mount data to host using compose/kubernetes/whatever
1. we merge this PR and it's being built.
1. the host does `docker image pull sitecore-xm-spe-sqldev:9.3.0-windowsservercore-ltsc2019` again
1. ... now we have bad databases since the old one 6.0.0 is being used but XM is on 6.1.1

**Comment by michaellwest** [comment]
Ah good point. Definitely a scenario I didn't think about.

**Comment by pbering** [comment]
yeah me either, that is why we have that problem now ;) ... we are currently discussing how to best handle it, you can see the different suggested conventions here: https://gist.github.com/pbering/d83e78afa7a1e574bceeb315c78a1429 but nothing is set in stone just yet. Personally my favorite is "Example 3 (Alternative B)".

**Comment by bic742** [comment]
How do we vote? I like Alternative A

**Comment by pbering** [comment]
We are waiting on input from Sitecore and how they will tag the platform images so we don't do something that is far off :)

I expect that we end up with A or B, I like both but for me it feels a bit strange to have version numbers in the repository part of the tag, even tough is expresses correctly what's in the image.

**Comment by jeanfrancoislarente** [comment]
@michaellwest - did you want to revisit this PR or should we abandon it?

**Comment by jeanfrancoislarente** [comment]
Sorry, should have been a question for @bic742 - did you want to revisit this PR or should we abandon it?

**Comment by bic742** [comment]
Let's just abandon it. If needed, I will create a new one to follow the new naming convention.

**Pull request closed without merging**
