### PR TITLE
Standardize the time output.

### PR DESCRIPTION
**Pull request by michaellwest**
Changed the output messages to no longer use '###'. Instead now it shows the time in a common format. Also updated Development.ps1 to include a switch to override the watcher. I don't see the need for this script to have many options.

### CODE REVIEW

**Comment by michaellwest** [comment]
image

**Comment by pbering** [comment]
The other PR #172 has now been merge so now you can update yours. Please also do your changes in the new /tools/entrypoints/worker/development.ps1 scripts (used for the xconnect worker roles)

**Comment by michaellwest** [comment]
@pbering Now the PR is just for the formatting changes to time.

**Comment by michaellwest** [comment]
I've only modified the ps1 files. Is there something in the PR you suspect broke the desired behavior?

**Comment by pbering** [comment]
looking at "windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Development.ps1" which is not formatted correctly, the same file for 9.2.0, 9.1.1 they are fine, only the 9.3.0 is bad.

**Comment by michaellwest** [comment]
You mean the issue is I formatted with the open bracket on the first one line? Six year old habits are hard to break.

**Comment by pbering** [comment]
Yes exactly :) you can then guess my habit :) ... ALT+SHIFT+F _should_ format it for you according to the .vscode\settings.json.

**Comment by pbering** [comment]
... which reminds me that we should write a contribution guide ...

**Comment by michaellwest** [comment]
Updates made to address formatting recommendation.

**Pull request merged**
