### PR TITLE
Added Global Download Support....

### PR DESCRIPTION
**Pull request by navancommits**
# Pull Request Checklist

## Image Details

- [N] I have added NEW image tags
- [N] I have made significant changes to existing images

## Pull Request Details

**What this PR does / why we need it**:
Added global download support.  Developers don't need to provide SitecoreUsername and SitecorePassword for Build.ps1 anymore. Creating a new PR since I had added the sitecore-tags.md in my earlier attempt. Removing as per jfl's advise.
**Which issue(s) this PR fixes**:NA

Fixes #
NA
**Special notes for your reviewer**:
Hi JFL, deleted my forked repo and added my changes again on a new fork since changes are minor. Hopefully this helps. And, thanks for responding quickly with the comments. If there is anything more I can do, please feel free to comment back. Although the package downloads happen fine, I see the following error, didn't get a chance to check this issue today:
ForEach-Object : The property 'OSType' cannot be found on this object. Verify that the property exists.
At C:\docker-images\build\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-Build.ps1:98 char:78
+ ... ormat '{{json .}}' | ConvertFrom-Json | ForEach-Object { $_.OSType })
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand

## Pre-submit Checklist

- [Y] I have read and am familiar with the contents of [CONTRIBUTING.md](https://github.com/Sitecore/docker-images/blob/master/CONTRIBUTING.md)
- [N] I have built the images locally (all relevant OS versions, including Linux if applicable)

  - Include the `.\build.ps1` command used (don't forget to exclude your credentials!)
  - .\Build.ps1 -Topology "xm", "xp" -SitecoreVersion "9.3.0"  -IncludeSpe -IncludeSxa
  - Ensure the build was done on a clean system (`docker system prune -af`)
  Yes
- [N] I have added or updated the necessary docker-compose file(s) in the `build/windows/tests` folder
- [Y] I have updated the documentation using `build\update-documentation.ps1`
- [Y] I have updated the `build\CHANGELOG.md` with details about the change(s) included

### CODE REVIEW

**Review by jeanfrancoislarente — CHANGES_REQUESTED** [review]
Thanks for the update!

So removing the username and password succeeded in downloading, so for the purposes of this PR I think we're good.

I'm not sure what the issue is with your build, it seems Docker related since the command works great locally for me.

One note is that the urls are still the "old" dev.sitecore.net urls and I think they're left there for legacy reasons. New CDN urls start with `https://sitecoredev.azureedge.net`. Could you do a search/replace on the urls in sitecore-packages.json and give it a test and submit? This way we'll take advantage of CDN urls.

Thanks!

**Comment by navancommits** [comment]
That's good info... updated the same... can see in the pr too... revert
back for anything further... thanks!

**Comment by navancommits** [comment]
I fixed "Property is not needed when ExpandProperty is used #305" to this PR, Will wait for this PR merge before I do any further changes... sorry for inconvenience if any....

**Review by jeanfrancoislarente — APPROVED** [review]
Ran through a build of 9.3.0, 10.0.0 and 10.0.1 - all assets downloaded as expected using the new urls.
Thanks!

**Comment by Mjazairi** [comment]
@navancommits how did you solve the OSType  property error? im facing the same issue now
image

**Comment by Mjazairi** [comment]
@navancommits  ok, i found it, i forgot to switch to windows containers after restarting, this solved the error 
image

**Pull request merged**
